TemplateProject/Controllers/JobsCustomController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TemplateProject.Models;

namespace TemplateProject.Controllers
{
    public class JobsCustomController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: JobsCustom
        public ActionResult Index()

        {
            var userId = User.Identity.GetUserId();
            var jobs = db.Jobs.Where(x=>x.UserId==userId);
            return View(jobs.ToList());
        }

        // GET: JobsCustom/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: JobsCustom/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: JobsCustom/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job , HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //Upload Image : 
                var guidImage = Guid.NewGuid()+upload.FileName;
                var path = Path.Combine(Server.MapPath("~/Uploads"), guidImage);
                upload.SaveAs(path);
                job.JobImage = guidImage;
                job.UserId = User.Identity.GetUserId();
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", job.CategoryId);
            return View(job);
        }

        // GET: JobsCustom/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", job.CategoryId);
            return View(job);
        }

        // POST: JobsCustom/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                var jobDb = db.Jobs.SingleOrDefault(x => x.Id == job.Id);
                if (upload != null)
                {
                    var guidPhoto = Guid.NewGuid() +upload.FileName;
             //update new photo :::
                    var path = Path.Combine(Server.MapPath("~/Uploads"), guidPhoto);
                    var oldPath = Path.Combine(Server.MapPath("~/Uploads"), job.JobImage);
                    upload.SaveAs(path);
                    System.IO.File.Delete(oldPath);
                    jobDb.JobImage = guidPhoto;
                }else
                {
                    //not uploaded new photo ::: 
                }
               // jobDb.JobImage = job.JobImage;
                jobDb.JobTitle = job.JobTitle;
                jobDb.JobContent = job.JobContent;
                jobDb.CategoryId = job.CategoryId;


                //db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", job.CategoryId);
            return View(job);
        }

        // GET: JobsCustom/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: JobsCustom/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id,HttpPostedFileBase upload)
        {
            Job job = db.Jobs.Find(id);
            var path = Path.Combine(Server.MapPath("~/Uploads"), job.JobImage);
            System.IO.File.Delete(path);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TemplateProject/Views/JobsCustom/Create.cshtml
@model TemplateProject.Models.Job
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm("Create", "JobsCustom", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="alert alert-danger" style="height:60px;display:none" id="alertDiv">
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="imgCheckBtn" />
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default" id="btnSave"> Create </button>
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts{
    <script>
    CKEDITOR.replace("JobContent");
        $(document).ready(function () {
//To remove alert danger when choose pic: 
            $("#imgCheckBtn").change(function () {
                $("#alertDiv").html("  ");
                $("#alertDiv").fadeOut("1000");
            })
//When we click on save button:
            $("#btnSave").click(function () {
//Check if empty:
                var checkImageExist = $("#imgCheckBtn").val();
                if (checkImageExist == "") {
                    $("#alertDiv").html("Please Choose An Image !!! ");
                    $("#alertDiv").fadeIn("3000");
                    return false;
                }
//Check file extension :
                var fileName = $("#imgCheckBtn").val();
                //ex: photo.png ===> png
                var extensionImage = fileName.substr(fileName.lastIndexOf('.') + 1).toLowerCase();
                debugger
                var arrOfExtensions = ["png", "jpg", "jif"];
//checke if extensionImage(png) exist in arrOfExtensions:
                if ($.inArray(extensionImage, arrOfExtensions) == -1) {
                    $("#alertDiv").html("Please Choose A Correct Image with standard extensions !!! ");
                    $("#alertDiv").fadeIn("3000");
                    return false;
                }
                //Check Image size => if size >2M 
                var fileName = document.getElementById("imgCheckBtn").files[0].size / 1024 / 1024;
                debugger
                if(fileName>2)
                {
                    $("#alertDiv").html("Please Choose Image with size less than 2 M !!! ");
                    $("#alertDiv").slideDown("3000");
                    return false;
                }
            })
        })
    </script>
}

TemplateProject/Views/JobsCustom/Delete.cshtml
@model TemplateProject.Models.Job

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.JobContent).ToString()))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Model.JobImage" style="width:140px;height:120px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TemplateProject/Views/JobsCustom/Details.cshtml
@model TemplateProject.Models.Job

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.JobContent).ToString()))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Model.JobImage" style="width:140px;height:120px;"/>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TemplateProject/Views/JobsCustom/Edit.cshtml
@model TemplateProject.Models.Job
@{
    ViewBag.Title = "Edit";
}
<h2>Edit</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm("Edit", "JobsCustom", FormMethod.Post, new { id=Model.Id}))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="alert alert-danger" style="height:60px;display:none" id="alertDiv">
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.JobImage)
        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">


                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="imgCheckBtn" />
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default" id="btnSave"> Edit </button>
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            CKEDITOR.replace("JobContent");
            $("#btnSave").click(function () {
                var imageVal = $("#imgCheckBtn").val();
                if (imageVal != "") {
//Check file extension :
                    var fileName = $("#imgCheckBtn").val();
                    //ex: photo.png ===> png
                    var extensionImage = fileName.substr(fileName.lastIndexOf('.') + 1).toLowerCase();
                    debugger
                    var arrOfExtensions = ["png", "jpg", "jif"];
//checke if extensionImage(png) exist in arrOfExtensions:
                    if ($.inArray(extensionImage, arrOfExtensions) == -1) {
                        $("#alertDiv").html("Please Choose A Correct Image with standard extensions !!! ");
                        $("#alertDiv").fadeIn("3000");
                        return false;
                    }
//Check Image size => if size >2M
                    var fileName = document.getElementById("imgCheckBtn").files[0].size / 1024 / 1024;
                    debugger
                    if (fileName > 2) {
                        $("#alertDiv").html("Please Choose Image with size less than 2 M !!! ");
                        $("#alertDiv").slideDown("3000");
                        return false;
                    }
                }
            })
        })
    </script>
}

TemplateProject/Views/JobsCustom/Index.cshtml
@model IEnumerable<TemplateProject.Models.Job>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(modelItem => item.JobContent).ToString()))
        </td>
        <td>
            <img class="img-thumbnail" src="~/Uploads/@item.JobImage" style="width:70px;height:70px;"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>